/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7deb8bfe-9f50-46d9-b2f3-85350db801ba",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_77Ns2VZoY",
    "aws_user_pools_web_client_id": "5rtillngn47a22321q3s2bu61o",
    "oauth": {}
};


export default awsmobile;
